version: '2.2'
services:
  monero:
    image: 'valentinvieriu/monero:${MONERO_VERSION}'
    build:
      context: .
      args:
        - MONERO_VERSION=${MONERO_VERSION}
        - MONERO_SHA=${MONERO_SHA}
    restart: 'unless-stopped'
    stdin_open: true
    ports:
        - 18080:18080
        - 18081:18081
    volumes:
      - ${ROOT_FOLDER}/blockchain:/root/.bitmonero
      # - ${ROOT_FOLDER}/wallets/monero_temp:/wallet
    command: ["--non-interactive","--log-level=0","--rpc-bind-ip=0.0.0.0", "--confirm-external-bind", "--fast-block-sync=1"]